# Generated by Django 4.1.3 on 2022-12-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=200)),
                ('mode', models.IntegerField()),
                ('userKey', models.IntegerField()),
                ('state', models.IntegerField()),
                ('dataUsePermission', models.BooleanField()),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.submissionresult')),
            ],
        ),
    ]
